name:                adventure
version:             0.1.0.0
github:              "jonathanlorimer/adventure"
license:             BSD3
author:              "Jonathan Lorimer"
maintainer:          "jonathan_lorimer@mac.com"
copyright:           "2020 Jonathan Lorimer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jonathanlorimer/adventure#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- containers
- microlens-th
- mtl
- text
- uuid
- vty

ghc-options: -Wall

default-extensions:
  - RankNTypes
  - OverloadedStrings
  - NamedFieldPuns

library:
  source-dirs: src

executables:
  adventure-time:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventure

tests:
  adventure-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventure
